create or replace FUNCTION FUN_LISTA_NO_PORTAFOLIO (VL_ID_PERFIL NUMBER)
RETURN VARCHAR2 IS
VL_NO_PORTAFOLIO VARCHAR2(1024);
VL_DSC_NO_PORTAFOLIO VARCHAR2(1024);

CURSOR C1 IS
    SELECT TRIM(por.NO_PORTAFOLIO) AS NO_PORTAFOLIO
    FROM TBL_PORTAFOLIO por 
    WHERE por.ES_REGISTRO='1' 
    AND por.ID_PERFIL = VL_ID_PERFIL
    ;
BEGIN
  OPEN C1;
  LOOP
    FETCH C1
      INTO VL_NO_PORTAFOLIO;
    EXIT WHEN C1%NOTFOUND;

    IF (VL_DSC_NO_PORTAFOLIO IS NULL) THEN
        VL_DSC_NO_PORTAFOLIO := VL_NO_PORTAFOLIO;
    ELSE 
         VL_DSC_NO_PORTAFOLIO := VL_DSC_NO_PORTAFOLIO || ', ' || VL_NO_PORTAFOLIO;
    END IF;
  END LOOP;
  CLOSE C1;
  RETURN VL_DSC_NO_PORTAFOLIO;  
END FUN_LISTA_NO_PORTAFOLIO;