create or replace FUNCTION FUN_LISTA_NO_SKILLSET (VL_ID_PERFIL NUMBER)
RETURN VARCHAR2 IS
VL_NO_SKILLSET VARCHAR2(1024);
VL_DSC_NO_SKILLSET VARCHAR2(1024);

CURSOR C1 IS
    SELECT TRIM(skl.NO_SKILLSET) AS NO_SKILLSET
    FROM TBL_SKILLSET skl 
    WHERE skl.ES_REGISTRO='1' 
    AND skl.ID_PERFIL = VL_ID_PERFIL
    ;
BEGIN
  OPEN C1;
  LOOP
    FETCH C1
      INTO VL_NO_SKILLSET;
    EXIT WHEN C1%NOTFOUND;

    IF (VL_DSC_NO_SKILLSET IS NULL) THEN
        VL_DSC_NO_SKILLSET := VL_NO_SKILLSET;
    ELSE 
         VL_DSC_NO_SKILLSET := VL_DSC_NO_SKILLSET || ', ' || VL_NO_SKILLSET;
    END IF;
  END LOOP;
  CLOSE C1;
  RETURN VL_DSC_NO_SKILLSET;  
END FUN_LISTA_NO_SKILLSET;