--------------------------------------------------------
-- Archivo creado  - sábado-enero-15-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_PERFIL
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."TBL_PERFIL" 
   (	"ID_PERFIL" NUMBER(19,0), 
	"AP_PERFIL" VARCHAR2(50 CHAR), 
	"COD_IMG" LONG RAW, 
	"DIR_PERFIL" VARCHAR2(75 CHAR), 
	"EMAIL_PERFIL" VARCHAR2(50 CHAR), 
	"ES_REGISTRO" VARCHAR2(1 CHAR), 
	"FE_ACTUALIZACION" TIMESTAMP (6), 
	"FE_CREACION" TIMESTAMP (6), 
	"FE_NACIMIENTO_PERFIL" TIMESTAMP (6), 
	"IMG_PERFIL" VARCHAR2(50 CHAR), 
	"IP_ACTUALIZACION" VARCHAR2(9 CHAR), 
	"IP_CREACION" VARCHAR2(9 CHAR), 
	"NO_PERFIL" VARCHAR2(50 CHAR), 
	"NU_DNI_PERFIL" NUMBER(19,0), 
	"TEL_PERFIL" NUMBER(19,0), 
	"TIPO_IMG" VARCHAR2(15 CHAR), 
	"US_ACTUALIZACION" VARCHAR2(10 CHAR), 
	"US_CREACION" VARCHAR2(10 CHAR), 
	"ID_UBIGEO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PORTAFOLIO.TBL_PERFIL
SET DEFINE OFF;
Insert into PORTAFOLIO.TBL_PERFIL (ID_PERFIL,AP_PERFIL,COD_IMG,DIR_PERFIL,EMAIL_PERFIL,ES_REGISTRO,FE_ACTUALIZACION,FE_CREACION,FE_NACIMIENTO_PERFIL,IMG_PERFIL,IP_ACTUALIZACION,IP_CREACION,NO_PERFIL,NU_DNI_PERFIL,TEL_PERFIL,TIPO_IMG,US_ACTUALIZACION,US_CREACION,ID_UBIGEO) values ('1','valerio',null,'Lima','jvalw@gmail.com','1',to_timestamp('14/01/22 11:52:17,288000000 PM','DD/MM/RR HH12:MI:SSXFF AM'),null,to_timestamp('10/10/99 12:00:00,000000000 AM','DD/MM/RR HH12:MI:SSXFF AM'),null,'127.0.0.0',null,'juan','74048099','960205949',null,'jvalerio',null,'221');
--------------------------------------------------------
--  DDL for Index SYS_C007092
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."SYS_C007092" ON "PORTAFOLIO"."TBL_PERFIL" ("ID_PERFIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_PERFIL
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."TBL_PERFIL" ADD PRIMARY KEY ("ID_PERFIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."TBL_PERFIL" MODIFY ("NU_DNI_PERFIL" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."TBL_PERFIL" MODIFY ("NO_PERFIL" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."TBL_PERFIL" MODIFY ("ES_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."TBL_PERFIL" MODIFY ("EMAIL_PERFIL" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."TBL_PERFIL" MODIFY ("AP_PERFIL" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."TBL_PERFIL" MODIFY ("ID_PERFIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_PERFIL
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."TBL_PERFIL" ADD CONSTRAINT "FKDQTMGSGCBOLYHR8UBH1UOW8R8" FOREIGN KEY ("ID_UBIGEO")
	  REFERENCES "PORTAFOLIO"."TBL_UBIGEO" ("ID_UBIGEO") ENABLE;
