  CREATE OR REPLACE FORCE VIEW "PORTAFOLIO"."VW_CURRICULUM_VITAE_AUX" ("ID_PERFIL", "NO_PERSONA", "NU_DNI_PERFIL", "TEL_PERFIL", "EMAIL_PERFIL", "DIR_PERFIL", "NO_PORTAFOLIO", "NO_SKILLSET", "TURNO", "SOBRE_MI", "RESUMEN") AS 
  SELECT 
pef.ID_PERFIL, pef.NO_PERFIL || ' ' || pef.AP_PERFIL AS NO_PERSONA
,pef.NU_DNI_PERFIL
,pef.TEL_PERFIL
,pef.EMAIL_PERFIL
,pef.DIR_PERFIL
,FUN_LISTA_NO_PORTAFOLIO(pef.ID_PERFIL) AS NO_PORTAFOLIO
,FUN_LISTA_NO_SKILLSET(pef.ID_PERFIL) AS NO_SKILLSET
,CASE 
    WHEN TO_CHAR(SYSDATE,'HH24:MI') BETWEEN '07:00:00' AND '11:59:59' THEN 'Buenos dias, '
    WHEN TO_CHAR(SYSDATE,'HH24:MI') BETWEEN '12:00:00' AND '18:59:59' THEN 'Buenas tardes, '
    ELSE 'Buenas noches, '
END AS TURNO
,pef.SOBRE_MI
,pef.RESUMEN
--, LISTAGG(por.NO_PORTAFOLIO, '; ') WITHIN GROUP (ORDER BY pef.ID_PERFIL) AS NO_PORTAFOLIO
--, LISTAGG(skl.NO_SKILLSET, '; ') WITHIN GROUP (ORDER BY skl.NO_SKILLSET) AS NO_SKILLSET
FROM TBL_PERFIL pef
--INNER JOIN TBL_PORTAFOLIO por ON (por.ID_PERFIL = pef.ID_PERFIL AND por.ES_REGISTRO = '1')
--INNER JOIN TBL_SKILLSET skl ON (skl.ID_PERFIL = pef.ID_PERFIL AND skl.ES_REGISTRO = '1')
;